### ISSUE TITLE
BUG: BRD Songs Loop with JA

### ISSUE THREAD

**Issue by Aezaeo** [eLiidyr/buddypal#11]
When having AutoJA on and using "//bp loop march march min min" the songs cast correctly with use of JAs but the recast of said songs is where the issue lies. It starts the recasting of the songs before the songs are even close to wearing off which causes one of the songs to be overwritten with a Paeon due to duration issues Im guessing.

Another thing Ive noticed, even when not using AutoJA and running in to the aforementioned issue, is, the jukebox always recasts the dummy songs when looping instead of just recasting the songs that are already active to avoid having to actually cast the dummy songs. If buddypal could determine how much time is left on songs that are on loop, which it already does or else it wouldn't loop properly, then it could just overwrite those same songs to extend the duration instead re-singing through the whole multiple dummy song loop.

Ex. //bp loop march march min > songs are cast with dummy songs to achieve the proper amount of songs > songs about to wear > recast march march min without using the dummy songs

Will save casting time and actual down time of the bard casting unnecessary dummy songs unless needed, i.e. no songs are active.

**Comment by eLiidyr** [comment]
Yeah, Ill look in to that one. I probably overlooked that entirely.
