### ISSUE TITLE
blu core ws issue

### ISSUE THREAD

**Issue by lightnencruser** [eLiidyr/buddypal#2]
elseif not bpcore:buffActive(272) and player["vitals"].tp > 1000 and system["Weapon"].en == "Lionheart" then
                            helpers["queue"].addToFront(WS["Resolution"], "t")
                        
                        elseif not bpcore:buffActive(272) and player["vitals"].tp > 1000 and system["Weapon"].en == "Epeolatry" then
                            helpers["queue"].addToFront(WS["Dimidiation"], "t")

Should be sword ws. Expiacion probably. Ideally would have the code that if Expiacion and clubs equipped then use Black halo ect.

**Comment by eLiidyr** [comment]
Just to note, only aftermath weapon skills are used in this particular code. You set your weapon skill that is to be used through commands. This would prevent the need to add hundreds of lines of 'if' statements to check for weapon skills. Expacion , along with   Chant du Cygne and Requiescat were to be inspected here other wise, but nothing else. Will be corrected in upcoming update tomorrow.
