### ISSUE TITLE
Impact

### ISSUE THREAD

**Issue by lightnencruser** [eLiidyr/buddypal#3]
Mage jobs probably should have an Impact option. probably a check if body is available then add to cast list? That said RDM should have it mainly.

**Comment by eLiidyr** [comment]
This ideally sounds like something that is more likely a gearswap functionality than a automated sequence. Im not sure how to go about making it possible with out also making it switch gear; which now in turn overwrites your gearswap sequence.
@lightnencruser 

I'm open to suggestions.
